In [105]:
import numpy as np

In [106]:
manifold=np.array([list(x) for x in input_data])

In [107]:
#determine initial beam
initial_beam_postion=np.where(manifold=="S")[1]
manifold[1][initial_beam_postion]="|"

In [108]:
manifold

array([['.', '.', '.', '.', '.', '.', '.', 'S', '.', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '|', '.', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '^', '.', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '.', '.', '^', '.', '^', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '.', '^', '.', '^', '.', '^', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '^', '.', '^', '.', '.', '.', '^', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '^', '.', '^', '.', '.', '.', '^', '.', '^', '.',
       

In [63]:
##all hat positions
split_postions=np.where(manifold=="^")

In [77]:
split_postions

(array([ 2,  4,  4,  6,  6,  6,  8,  8,  8, 10, 10, 10, 10, 12, 12, 12, 14,
        14, 14, 14, 14, 14]),
 array([ 7,  6,  8,  5,  7,  9,  4,  6, 10,  3,  5,  9, 11,  2,  6, 12,  1,
         3,  5,  7,  9, 13]))

In [130]:
input_data=['.......S.......',
'...............',
'.......^.......',
'...............',
'......^.^......',
'...............',
'.....^.^.^.....',
'...............',
'....^.^...^....',
'...............',
'...^.^...^.^...',
'...............',
'..^...^.....^..',
'...............',
'.^.^.^.^.^...^.',
'...............']

In [131]:
import numpy as np

In [132]:
manifold=np.array([list(x) for x in input_data])

In [133]:
#determine initial beam
initial_beam_postion=np.where(manifold=="S")[1]
manifold[1][initial_beam_postion]="|"

In [120]:
##function for index positions of incoming beams
current_line=2
incoming_beams=np.where(manifold[current_line-1]=="|")

In [123]:
if manifold[current_line][(incoming_beams[0])]=="^":
    manifold[current_line,(incoming_beams[0])+1]="|"
    manifold[current_line,(incoming_beams[0])-1]="|"

if manifold[current_line][(incoming_beams[0])]==".":
    manifold[current_line,(incoming_beams[0])]="|"

In [140]:
for current_line in range(2,len(manifold)):
    incoming_beams=np.where(manifold[current_line-1]=="|")
    
    if manifold[current_line][(incoming_beams[0] [0])]=="^":
        manifold[current_line,(incoming_beams[0] [0])+1]="|"
        manifold[current_line,(incoming_beams[0] [0])-1]="|"

    if manifold[current_line][(incoming_beams[0] [0])]==".":
        manifold[current_line,(incoming_beams[0] [0])]="|"
        
    


In [147]:
import util
file_path='/Users/danielmitic/Downloads/input.txt'
input_data=util.read_file_into_lines(file_path)

In [148]:
import numpy as np

In [149]:
manifold=np.array([list(x) for x in input_data])

In [150]:
#determine initial beam
initial_beam_postion=np.where(manifold=="S")[1]
manifold[1][initial_beam_postion]="|"

In [151]:
## liwia
raycounter = 0
for x in range(2,len(manifold)):
    for i in range(len(manifold[x])):
        if manifold[x][i] == "^" and manifold[x-1][i] == "|":
            manifold[x][i-1] = "|"
            manifold[x][i+1] = "|"
            raycounter +=1
        if manifold[x][i] == "." and manifold[x-1][i] == "|":
            manifold[x][i] = "|" 

for line in manifold:
    print(''.join(line))
raycounter

......................................................................S......................................................................
......................................................................|......................................................................
.....................................................................|^|.....................................................................
.....................................................................|.|.....................................................................
....................................................................|^|^|....................................................................
....................................................................|.|.|....................................................................
...................................................................|^|||^|...................................................................
......

1516

In [139]:
incoming_beams[]

(array([6, 8]),)