In [2]:
input_data=['.......S.......',
'.......|.......',
'......|^|......',
'......|.|......',
'.....|^|^|.....',
'...............',
'.....^.^.^.....',
'...............',
'....^.^...^....',
'...............',
'...^.^...^.^...',
'...............',
'..^...^.....^..',
'...............',
'.^.^.^.^.^...^.',
'...............']

In [4]:
input_data=['.......S.......',
'...............',
'.......^.......',
'...............',
'......^.^......',
'...............',
'.....^.^.^.....',
'...............',
'....^.^...^....',
'...............',
'...^.^...^.^...',
'...............',
'..^...^.....^..',
'...............',
'.^.^.^.^.^...^.',
'...............']

In [8]:
initial_beam_location=input_data[0].index("S")

In [10]:
input_data[1]

'...............'

In [104]:
input_data=['.......S.......',
'...............',
'.......^.......',
'...............',
'......^.^......',
'...............',
'.....^.^.^.....',
'...............',
'....^.^...^....',
'...............',
'...^.^...^.^...',
'...............',
'..^...^.....^..',
'...............',
'.^.^.^.^.^...^.',
'...............']

In [105]:
import numpy as np

In [106]:
manifold=np.array([list(x) for x in input_data])

In [107]:
#determine initial beam
initial_beam_postion=np.where(manifold=="S")[1]
manifold[1][initial_beam_postion]="|"

In [108]:
manifold

array([['.', '.', '.', '.', '.', '.', '.', 'S', '.', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '|', '.', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '^', '.', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '.', '.', '^', '.', '^', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '.', '^', '.', '^', '.', '^', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '^', '.', '^', '.', '.', '.', '^', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '^', '.', '^', '.', '.', '.', '^', '.', '^', '.',
       

In [63]:
##all hat positions
split_postions=np.where(manifold=="^")

In [77]:
split_postions

(array([ 2,  4,  4,  6,  6,  6,  8,  8,  8, 10, 10, 10, 10, 12, 12, 12, 14,
        14, 14, 14, 14, 14]),
 array([ 7,  6,  8,  5,  7,  9,  4,  6, 10,  3,  5,  9, 11,  2,  6, 12,  1,
         3,  5,  7,  9, 13]))

In [84]:
for i in range(len(split_postions[0])):
    x=split_postions[0][i]
    y=split_postions[1][i]

    

    

    manifold[x,y+1]="|"
    manifold[x,y-1]="|"
    manifold[x+1,y+1]="|"
    manifold[x+1,y-1]="|"

In [88]:
manifold

array([['.', '.', '.', '.', '.', '.', '.', 'S', '.', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '|', '.', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '.', '.', '|', '^', '|', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '.', '.', '|', '.', '|', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '.', '|', '^', '|', '^', '|', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '.', '|', '.', '|', '.', '|', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '|', '^', '|', '^', '|', '^', '|', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '|', '.', '|', '.', '|', '.', '|', '.', '.',
        '.', '.'],
       ['.', '.', '.', '|', '^', '|', '^', '|', '.', '|', '^', '|', '.',
        '.', '.'],
       ['.', '.', '.', '|', '.', '|', '.', '|', '.', '|', '.', '|', '.',
        '.', '.'],
       ['.', '.', '|', '^', '|', '^', '|', '.', '|', '^', '|', '^', '|',
       

In [130]:
input_data=['.......S.......',
'...............',
'.......^.......',
'...............',
'......^.^......',
'...............',
'.....^.^.^.....',
'...............',
'....^.^...^....',
'...............',
'...^.^...^.^...',
'...............',
'..^...^.....^..',
'...............',
'.^.^.^.^.^...^.',
'...............']

In [131]:
import numpy as np

In [132]:
manifold=np.array([list(x) for x in input_data])

In [133]:
#determine initial beam
initial_beam_postion=np.where(manifold=="S")[1]
manifold[1][initial_beam_postion]="|"

In [120]:
##function for index positions of incoming beams
current_line=2
incoming_beams=np.where(manifold[current_line-1]=="|")

In [123]:
if manifold[current_line][(incoming_beams[0])]=="^":
    manifold[current_line,(incoming_beams[0])+1]="|"
    manifold[current_line,(incoming_beams[0])-1]="|"

if manifold[current_line][(incoming_beams[0])]==".":
    manifold[current_line,(incoming_beams[0])]="|"

In [140]:
for current_line in range(2,len(manifold)):
    incoming_beams=np.where(manifold[current_line-1]=="|")
    
    if manifold[current_line][(incoming_beams[0] [0])]=="^":
        manifold[current_line,(incoming_beams[0] [0])+1]="|"
        manifold[current_line,(incoming_beams[0] [0])-1]="|"

    if manifold[current_line][(incoming_beams[0] [0])]==".":
        manifold[current_line,(incoming_beams[0] [0])]="|"
        
    


In [145]:
incoming_beams

(array([0, 2]),)

In [141]:
manifold

array([['.', '.', '.', '.', '.', '.', '.', 'S', '.', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '|', '.', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '.', '.', '|', '^', '|', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '.', '.', '|', '.', '.', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '.', '|', '^', '|', '^', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '.', '|', '.', '.', '.', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '|', '^', '|', '^', '.', '^', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '.', '|', '.', '.', '.', '.', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '.', '|', '^', '|', '^', '.', '.', '.', '^', '.', '.',
        '.', '.'],
       ['.', '.', '.', '|', '.', '.', '.', '.', '.', '.', '.', '.', '.',
        '.', '.'],
       ['.', '.', '|', '^', '|', '^', '.', '.', '.', '^', '.', '^', '.',
       

In [139]:
incoming_beams[]

(array([6, 8]),)